### ISSUE TITLE
Overlapping accesses to 'self.grid'

### ISSUE THREAD

**Issue by pdegouville** [hollance/Matrix#3]
I have been using the Matrix project for quiet a long time. I decided to migrate my project to XCode 9.4 .1 and I have encountered this warning:

 Overlapping accesses to 'self.grid', but modification requires exclusive access; consider copying to a local variable

This warning appears several time in Matrix.Swift

```
    grid.withUnsafeMutableBufferPointer { dst in
      for (i, row) in data.enumerated() {
        row.withUnsafeBufferPointer { src in
          cblas_dcopy(Int32(n), src.baseAddress! + range.lowerBound, 1, dst.baseAddress! + i*columns, 1)
        }
      }
    }
```

or there for instance:

```
public func transpose() -> Matrix {
    var results = Matrix(rows: columns, columns: rows, repeatedValue: 0)
    grid.withUnsafeBufferPointer { srcPtr in
      results.grid.withUnsafeMutableBufferPointer { dstPtr in
        vDSP_mtransD(srcPtr.baseAddress!, 1, dstPtr.baseAddress!, 1, vDSP_Length(results.rows), vDSP_Length(results.columns))
      }
    }
    return results
  }

```

The code still compiles and seems to run correctly. Do you have any idea ?
Thks

**Comment by hollance** [comment]
Hmm, it's not entirely clear to me why you would get those warnings in these methods. But where I've seen them it was usually sufficient to make a `var somePointer = ...` variable and use that instead.

**Comment by pdegouville** [comment]
OK. I followed your advice and it works. But it is weird anayway !
