### ISSUE TITLE
Xcode 12 pointer error

### ISSUE THREAD

**Issue by ozgurshn** [hollance/Matrix#6]
Hi Hollemans, starting with Xcode 12, this adding part started to give compiler error. How can I resolve this issue?

Error: Generic parameter 'Element' could not be inferred
Warning: Inout expression creates a temporary pointer, but argument #1 should be a pointer that outlives the call to '+'

![image](https://user-images.githubusercontent.com/2404074/94134009-1d501f00-fe6a-11ea-937e-bbbdfb90a9e1.png)

**Comment by Legoless** [comment]
Easy:
```
v.grid.withUnsafeBufferPointer { src in
        grid.withUnsafeMutableBufferPointer { target in
          cblas_dcopy(Int32(rows), src.baseAddress, 1, target.baseAddress! + c, Int32(columns))
        }
      }
```

**Comment by ozgurshn** [comment]
Thanks @Legoless that solved the problem. Submitted a PR fixing this issue https://github.com/hollance/Matrix/pull/7.
